site:
  name: Binary Craft
  site: 'https://binarycraft.dev'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Binary Craft
    template: '%s — Binary Craft'
  description: 'Web development services'
  robots:
    index: false
    follow: false
  openGraph:
    site_name: BinaryCraft
    images:
      - url: '~/assets/images/iso-white.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
